import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Post from '../components/post/Post'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My Posts
        </h1>

        <ul className ={styles.posts}>
          <li>
            <Post content = "Hey, I am a new post!" date="08/09/2021" />
          </li>
          <li>
          <Post content = "Hey, I am a new post!" date="08/09/2021" />
          </li>
          <li>
          <Post content = "Hey, I am a new post!" date="08/09/2021" />
          </li>
        </ul>
        
        <form>
          <textarea className={styles.formContent}>
            
          </textarea>
          <button className={styles.formButt}> Add New Post </button>
        </form>
      </main>
    </div>
  )
}
