import Head from 'next/head'
import Bio from '../components/Bio';
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Post from '../components/post/Post'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        <Bio
          headshot='https://images.unsplash.com/photo-1597223557154-721c1cecc4b0?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'
          name = "Samantha Fayokh"
          tagline = "Expressing myself through words"
          role = "Journalist @ ABC"
        />
        </h1>

        <ul className ={styles.posts}>
          <li>
            <Post content = "Hey, I am a new post!" date="08/09/2021" />
          </li>
          <li>
          <Post content = "Hey, I am a new post!" date="08/09/2021" />
          </li>
          <li>
          <Post content = "Hey, I am a new post!" date="08/09/2021" />
          </li>
        </ul>
        
        <form>
          <textarea className={styles.formContent}>
            
          </textarea>
          <button className={styles.formButt}> Add New Post </button>
        </form>
      </main>
    </div>
  )
}
